### ISSUE TITLE
Create Feedback DB model

### ISSUE THREAD

**Issue by coltonehrman** [Software-Developer-Academy/mentor-match#67]
Related to #66 

Create new mongoose model/schema for Feedback submitted by users.

**Comment by Ramzi-Abidi** [comment]
Hi, I want to work on this issue, can you assign it to me!

**Comment by Ramzi-Abidi** [comment]
Could you please explain what does feedback schema/model contains, or if there's any documentation available on the models used in the app? 😅

**Comment by tjay22** [comment]
> Could you please explain what does feedback schema/model contains, or if there's any documentation available on the models used in the app? 😅

@Ramzi-Abidi We don't have a feedback model/schema yet so the freedom is yours to create a model you think will work best for the app. I guess the fields we can start off with are userId, feedback and rating? I don't know if capturing time and date are important.

**Comment by KQuiggins** [comment]
You can just add timestamps:true to the model to collect them if you want, I always add it to almost all my models just in case I ever need them. It may be a good idea for reviews because most reviews have a time & date on them if you look online at any reviews. Really up to you though
![timestamps](https://github.com/Software-Developer-Academy/mentor-match/assets/76880191/cc3c6660-66fb-43eb-a70d-3ae9e6bc42df)

**Comment by Ramzi-Abidi** [comment]
@KQuiggins Clear!
